spring:
  application:
    name: @project.name@

  datasource:
    url: jdbc:h2:file:./data/ecommerce_db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

controller:
  properties:
    base-path: /@project.name@

app:
  security:
    key: "V1RjeVdUQXlPVFE1TkRReU1qUXhNRFkzTlRRNU9EazNNZz09"
